add test for circuit parser
Qulacs-Osaka/qulacs-visualizer pull request #50
Opened 2021-12-16 02:25 UTC by kawamochi

テスト追加しました

CI通ったらマージしてOKです

2021-12-17 08:49 UTC, Hiroya-W commented
出来る限り、ちゃんとレビューした方がいいと思っています。よく見ると、これのテスト実行されてないです…。

2021-12-17 08:53 UTC, Hiroya-W requested changes
テストの追加ありがとうございます！Exampleの5つで十分であるかは今後見極めていきたいですが、ひとまずこれをpassするようにしたいですね。

修正箇所をコメントしているので、修正お願いします！

2021-12-17 08:53 UTC, Hiroya-W commented on tests/circuit_parser_test.py
> +def circuit_parser_test1() -> None:
関数名は`test_`で始まるようにしないとpytestでの実行対象にならないです。例えば、以下のようにすると良いです。

```suggestion
def test_circuit_parser_example1() -> None:
```

2021-12-17 08:53 UTC, Hiroya-W commented on tests/circuit_parser_test.py
> +def circuit_parser_test2() -> None:
関数名は`test_`で始まるようにします。

2021-12-17 08:53 UTC, Hiroya-W commented on tests/circuit_parser_test.py
> +def circuit_parser_test3() -> None:
関数名は`test_`で始まるようにします。

2021-12-17 08:53 UTC, Hiroya-W commented on tests/circuit_parser_test.py
> +def circuit_parser_test4() -> None:
関数名は`test_`で始まるようにします。

2021-12-17 08:53 UTC, Hiroya-W commented on tests/circuit_parser_test.py
> +def circuit_parser_test5() -> None:
関数名は`test_`で始まるようにします。

2021-12-17 08:56 UTC, Hiroya-W commented
今回みたいに、テストの中身の実行方法が同じ場合は`pytest.mark.parametrize`が使えます。テーブル駆動テストとも呼ばれますが、テストデータを用意すれば、テストの関数は1つで良くなるので、もし余力があれば試してみてください。

https://docs.pytest.org/en/6.2.x/parametrize.html#pytest-mark-parametrize

2021-12-17 08:58 UTC, Hiroya-W commented
例えば、tests/matplotlib_test.py で使っています。`pytest.mark.mpl_image_compare`はmatplotlib用のテストの書き方なので、今回は無視しても大丈夫です。
参考になると思いますが、もし分からなければ教えるので、連絡してください。

2021-12-17 09:46 UTC, kotamanegi reviewed
突然のレビュー失礼します。
テストを追加してくださりありがとうございます！

番号だけでなくテストケースの特徴を説明に含めた方がより良いと思います。具体的に名前をどう変えるかというのは理解できていないのですが、CNOTが含まれているとかそういった情報を入れた方が良いのではないでしょうか。
また、expectedがとても長いのでコードの可読性を失っている気がします。別ファイルやexpectedの情報を返す関数として分離できないでしょうか？

2021-12-21 05:15 UTC, Hiroya-W commented
> 番号だけでなくテストケースの特徴を説明に含めた方がより良いと思います

これはその通りですね。`example1`という例も良くなかったです。

2021-12-21 05:22 UTC, Hiroya-W commented
> 具体的に名前をどう変えるか

`pytest.mark.parametrize`を使う場合は、`id`に文字列を入れたテストデータを作っておくと実現できます。例えば、pytestのexamplesには
https://docs.pytest.org/en/6.2.x/example/parametrize.html#paramexamples

```py
@pytest.mark.parametrize(
    "a,b,expected",
    [
        pytest.param(
            datetime(2001, 12, 12), datetime(2001, 12, 11), timedelta(1), id="forward"
        ),
        pytest.param(
            datetime(2001, 12, 11), datetime(2001, 12, 12), timedelta(-1), id="backward"
        ),
    ],
)
def test_timedistance_v3(a, b, expected):
    diff = a - b
    assert diff == expected
```

pytestの実行時には以下のように表示されるようになります。

```
  <Function test_timedistance_v3[forward]>
  <Function test_timedistance_v3[backward]>
```

2021-12-21 05:29 UTC, Hiroya-W commented
> また、expectedがとても長いのでコードの可読性を失っている気がします。別ファイルやexpectedの情報を返す関数として分離できないでしょうか？

jsonファイルとして書き出しておいて、正解データをそこから読み込むのはどうでしょうか。matplotlib用に画像の比較では、画像のhash値を`tests/baseline/hash/*.json`に置いているので、同様に`tests/baseline/circuit_parser/*.json`のように配置してもいいと思います。

2022-02-04 05:24 UTC, Hiroya-W commented
@kawamochi この修正、現状どうなっていますか？

2022-03-14 04:42 UTC, merged